# This is a basic workflow to help you get started with Actions

name: deploy_css

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  create:
    tags:
      - v*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Make destination directory for compiled CSS
        run: mkdir -vp assets/styles/css

      - name: Install SASS
        run: npm i -g sass

      - name: Compile CSS from SCSS files
        run: sass assets/styles/scss/main.scss assets/styles/css/styles.css

      #TODO Do merges to main
      - name: Merging to main for GitHub Pages Deploy
        run: |
             git config --global user.name "Sylvain Roux"
             git config --global user.email fafmio@outlook.fr
             git config --global user.password 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
             git git branch dev || git switch dev
             git merge dev

